### ISSUE TITLE
Turncost for main roads

### ISSUE THREAD

**Issue by utack** [poutnikl/Brouter-profiles#9]
I wanted to ask about turncost for main roads  
  
    assign turncost       if  ismainroad  then 90    else if ispaved then 60   else 30  
  
Maybe 90 is a bit high.  
Often when I go down from a mainroad, I have better vision of what is happening, than when I have to turn in small residential sideroads, and don't have to slow down much more  
The tecking-dry also produces something odd [here](http://brouter.de/brouter-web/#zoom=18&lat=48.040059&lon=11.522469&layer=OpenStreetMap&lonlats=11.522791,48.039518|11.522384,48.04035&nogos=&alternativeidx=0&format=geojson)  
![bildschirmfoto vom 2017-01-12 15-07-26](https://cloud.githubusercontent.com/assets/8551234/21892824/e7b55c62-d8d8-11e6-83f2-677049731f34.png)

Just a discussion, I am not entirely certain it is a good idea, but I tried many routes and none got worse, and this problem above was fixed  
Also the argument from experience above would tell me that turncost might be the same on small and large roads, in average

**Comment by poutnikl** [comment]
Turncost BRouter parameter addresses any physical turning, as an estimated loss of distance due slowing down. Turning on main roads are considered more costly, as you are supposed going faster, and the distance loss by breaking, going on lower speed and accelerating back is bigger.

Note also that BRouter default Trekking profile uses turncost 90 for all roads, ańd I decreased it for small roads. OTOH, it sets turncost=0 and costfactor=1.0 for cycleroutes, unless ignore cycleroutes is chosen.
( actual_turncost = turncost * ( 1 - cos(alfa)) . 

Not sharp, round-like turning is mapped in OSM as a serie of small turns, so effect is like 
e.g. 4 * turncost * ( 1 - cos(22.5)), instead of turncost.

Trekking-dry selected smaller roads mainly because secondary is not liked by the profile, and it was avoiding the traffic light.
 
What I may reconsider is initialcost management, increasing initialcost for small ways. ( Default Trekking does not use initialcost for ways)

You may easily follow the evaluation of way segments on the data tab of BRouter web.

I admit the profile is focussed more on rural area trekking than on city biking. It is possible city would need different tuning. There is need of balanced costfactors and initialcosts.

**Comment by poutnikl** [comment]
When I changed at  **assign initialcost** statement the ending   **else 0**  to **else 30**, the result routing was the same as for the Trekking profile, e.g. along the main roads.

I may also reconsider the lowering cost of traffic lights.

**Comment by poutnikl** [comment]
[V2.5.8-changed initial costs for minor ways](https://github.com/poutnikl/Trekking-Poutnik/commits/master/Trekking-Poutnik.brf)

**Comment by utack** [comment]
Thanks!  
I hope it leads to consistently better results

**Comment by utack** [comment]
Initialcost 10 also fixes the "many small ways" thing, but it does not influence some larger routes I tried

**Comment by poutnikl** [comment]
The point is, in the dense way network as there is in cities, there is needed a trade-off  between
 * low enough initial costs  to still prefer bike friendly roads
 * high enough initial costs to avoid too frequent road jumping.
The shorter way segments there are, the more significant are initialcosts , and less the costfactors.
It makes the difference, if the way connection nodes are 1 per 1-2 km on rural areas, or 1 per 20-50m in cities.

**Comment by utack** [comment]
Yes that is exactly what solves the problem I found, much better than messing with turncosts
